<?php
namespace Sentinel\Rpc;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * sentinel 客户端与 sidecar 通信的底层 RPC 接口定义。
 * 
 */
interface SentinelRpcIf
{
    /**
     * @param string $name
     * @return int
     * @throws \Sentinel\BlockException
     */
    public function entry($name);
    /**
     * 释放资源。
     * 
     * java 使用 "exit", 但 "exit" 是 php 关键字, php 7.0 才支持使用其作为自定义名字.
     * 修改为使用 "close" 以增强兼容性。
     * 
     * 
     * @param int $id
     */
    public function close($id);
}
